const styles = {
    root: {
        '--bg-base': '#070707',
        '--bg-surface': '#111111',
        '--bg-highlight': '#1a1a1a',
        '--border': '#262626',
        '--border-light': '#333333',
        '--text-main': '#f4f4f4',
        '--text-muted': '#8a8a8a',
        '--text-dark': '#555555',
        '--accent': '#F05D38',
        '--accent-dim': 'rgba(240, 93, 56, 0.15)',
        '--font-sans': "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
        '--font-mono': "'JetBrains Mono', 'Fira Code', monospace",
        '--grid-gap': '1px',
    },
    body: {
        backgroundColor: '#070707',
        color: '#f4f4f4',
        fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
        lineHeight: '1.6',
        padding: '2vw',
        minHeight: '100vh',
        display: 'flex',
        justifyContent: 'center',
        fontSize: '15px',
        WebkitFontSmoothing: 'antialiased',
        MozOsxFontSmoothing: 'grayscale',
    },
    systemFrame: {
        width: '100%',
        maxWidth: '1400px',
        backgroundColor: '#262626',
        border: '1px solid #262626',
        display: 'grid',
        gridTemplateColumns: '320px 1fr',
        gap: '1px',
    },
    panel: {
        backgroundColor: '#070707',
        padding: '40px',
        position: 'relative',
    },
    panelSurface: {
        backgroundColor: '#111111',
        padding: '40px',
        position: 'relative',
    },
    sidebar: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1px',
        background: '#262626',
    },
    profilePicContainer: {
        width: '100%',
        aspectRatio: '1',
        background: '#070707',
        position: 'relative',
        display: 'flex',
        justifyContent: 'center',
        overflow: 'hidden',
        padding: '0',
    },
    profilePhoto: {
        width: '100%',
        height: '100%',
        objectFit: 'cover',
        objectPosition: 'top',
        zIndex: 1,
        display: 'block',
    },
    profilePicGrid: {
        position: 'absolute',
        inset: '0px',
        border: '1px solid #333333',
        backgroundImage: 'linear-gradient(90deg, #111111 1px, transparent 1px), linear-gradient(0deg, #111111 1px, transparent 1px)',
        backgroundSize: '20px 20px',
    },

    profilePicCenter: {
        width: '40%',
        height: '40%',
        border: '1px solid #F05D38',
        position: 'relative',
        zIndex: 1,
        background: 'rgba(240, 93, 56, 0.05)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontFamily: "'JetBrains Mono', monospace",
        color: '#F05D38',
        fontSize: '24px',
    },
    sysBadge: {
        position: 'absolute',
        top: '24px',
        right: '24px',
        fontFamily: "'JetBrains Mono', monospace",
        fontSize: '0.7rem',
        color: '#555555',
        border: '1px solid #262626',
        padding: '4px 8px',
        textTransform: 'uppercase',
        background: '#070707',
        zIndex: 2,
    },
    h2: {
        fontFamily: "'JetBrains Mono', monospace",
        fontSize: '0.85rem',
        textTransform: 'uppercase',
        letterSpacing: '0.1em',
        color: '#8a8a8a',
        marginBottom: '24px',
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
    },
    kvList: {
        listStyle: 'none',
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
    },
    kvItem: {
        display: 'flex',
        flexDirection: 'column',
        gap: '4px',
    },
    kvKey: {
        fontFamily: "'JetBrains Mono', monospace",
        fontSize: '0.75rem',
        color: '#555555',
        textTransform: 'uppercase',
    },
    kvVal: {
        fontWeight: '500',
        color: '#f4f4f4',
    },
    kvValMono: {
        fontFamily: "'JetBrains Mono', monospace",
        fontWeight: '500',
        color: '#f4f4f4',
    },
    mainContent: {
        display: 'flex',
        flexDirection: 'column',
        gap: '1px',
        background: '#262626',
    },
    heroPanel: {
        padding: '60px 40px',
        backgroundColor: '#070707',
        position: 'relative',
    },
    h1: {
        fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
        fontWeight: '700',
        fontSize: '3.5rem',
        letterSpacing: '-0.04em',
        lineHeight: '1',
        marginBottom: '0.5rem',
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
        color: '#f4f4f4',
    },
    roleTitle: {
        fontFamily: "'JetBrains Mono', monospace",
        color: '#F05D38',
        fontSize: '1rem',
        marginBottom: '24px',
        display: 'block',
    },
    summaryText: {
        fontSize: '1.125rem',
        lineHeight: '1.7',
        maxWidth: '800px',
        color: '#8a8a8a',
    },
    techGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(4, 1fr)',
        gap: '1px',
        background: '#262626',
        borderTop: '1px solid #262626',
    },
    techCategory: {
        backgroundColor: '#111111',
        padding: '32px 24px',
    },
    techCategoryTitle: {
        fontFamily: "'JetBrains Mono', monospace",
        fontSize: '0.75rem',
        color: '#555555',
        marginBottom: '16px',
        textTransform: 'uppercase',
        borderBottom: '1px solid #262626',
        paddingBottom: '8px',
    },
    techList: {
        listStyle: 'none',
        display: 'flex',
        flexDirection: 'column',
        gap: '8px',
    },
    projectHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'baseline',
        marginBottom: '16px',
        borderBottom: '1px dashed #333333',
        paddingBottom: '16px',
    },
    projectMeta: {
        fontFamily: "'JetBrains Mono', monospace",
        fontSize: '0.85rem',
        color: '#F05D38',
    },
    archDiagram: {
        display: 'flex',
        alignItems: 'center',
        gap: '16px',
        margin: '32px 0',
        fontFamily: "'JetBrains Mono', monospace",
        fontSize: '0.75rem',
        color: '#8a8a8a',
        overflowX: 'auto',
        paddingBottom: '8px',
    },
    node: {
        border: '1px solid #333333',
        padding: '8px 12px',
        background: '#1a1a1a',
        whiteSpace: 'nowrap',
    },
    nodeAccent: {
        border: '1px solid rgba(240, 93, 56, 0.15)',
        padding: '8px 12px',
        background: '#1a1a1a',
        whiteSpace: 'nowrap',
        color: '#F05D38',
    },
    connector: {
        flexGrow: 1,
        height: '1px',
        background: '#333333',
        minWidth: '20px',
        position: 'relative',
    },
    ctaPanel: {
        backgroundColor: '#F05D38',
        color: '#070707',
        padding: '60px 40px',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        textDecoration: 'none',
        cursor: 'pointer',
        transition: 'background-color 0.3s ease',
    },
    ctaText: {
        fontSize: '2rem',
        fontWeight: '700',
        letterSpacing: '-0.02em',
        color: '#070707',
    },
    refIcon: {
        display: 'inline-flex',
        width: '24px',
        height: '24px',
        stroke: '#8a8a8a',
        strokeWidth: '1.5',
        strokeLinecap: 'square',
        strokeLinejoin: 'miter',
        fill: 'none',
    },
    codeEl: {
        fontFamily: "'JetBrains Mono', monospace",
        background: '#1a1a1a',
        color: '#f4f4f4',
        padding: '2px 6px',
        borderRadius: '2px',
        fontSize: '0.85em',
        border: '1px solid #333333',
    },
};
export default styles;